[package]
name = "datamatrix"
version = "0.1.0"
authors = ["Jannik Schürg <jannik.schuerg+crates@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.5.2"